# Generated by Django 5.2.9 on 2026-01-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('contenu_texte', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='utilisateurs.utilisateur')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-created_at'],
            },
        ),
    ]
