# Generated by Django 5.2.9 on 2026-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='depot_physique_postuler',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse de dépôt physique'),
        ),
        migrations.AddField(
            model_name='publication',
            name='email_postuler',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='publication',
            name='telephone_postuler',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact'),
        ),
        migrations.AddField(
            model_name='publication',
            name='whatsapp_postuler',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien WhatsApp'),
        ),
    ]
