# Generated by Django 5.2.9 on 2026-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lien_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Lien email'),
        ),
        migrations.AddField(
            model_name='publication',
            name='lien_site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Lien site web'),
        ),
        migrations.AddField(
            model_name='publication',
            name='lien_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien WhatsApp'),
        ),
    ]
