# Generated by Django 5.2.9 on 2026-02-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_lien_email_publication_lien_site_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='video',
        ),
    ]
