# Generated by Django 5.2.9 on 2026-03-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publicationimage'),
        ('publications', '0008_alter_publication_contact_nullable'),
    ]

    operations = [
    ]
