# Generated by Django 5.2.11 on 2026-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_merge_20260328_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='domaine',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
