# Generated by Django 5.2.9 on 2026-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('photo_profil', models.CharField(blank=True, max_length=500, null=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'ordering': ['-id'],
            },
        ),
    ]
